# UTF-8エンコーディングでコンソール出力を設定
[Console]::OutputEncoding = [System.Text.Encoding]::UTF8

Write-Host ""
Write-Host "==============================================="
Write-Host "Llasa Batch Generation Mode / Llasa バッチ生成モード"
Write-Host "==============================================="
Write-Host ""
Write-Host "Usage / 使用方法:"
Write-Host "  Drag and drop audio files or folders to BatchGenerate.bat"
Write-Host "  音声ファイルまたはフォルダをBatchGenerate.batにドラッグおよびドロップ"
Write-Host ""
Write-Host "What it does / 動作内容:"
Write-Host "  1. Takes your audio file(s) as voice reference"
Write-Host "     音声ファイルを声の参照として使用"
Write-Host "  2. Reads text lines from Dialogue.txt"
Write-Host "     Dialogue.txtからテキスト行を読み込み"
Write-Host "  3. Generates new audio files for each text line"
Write-Host "     各テキスト行に対して新しい音声ファイルを生成"
Write-Host "  4. Saves all generated files to Output folder"
Write-Host "     生成されたファイルをすべてOutputフォルダに保存"
Write-Host ""
Write-Host "Examples / 例:"
Write-Host "  - Drag sample_voice.wav to BatchGenerate.bat"
Write-Host "    sample_voice.wavをBatchGenerate.batにドラッグ"
Write-Host "  - Drag audio folder containing multiple files"
Write-Host "    複数の音声ファイルを含むフォルダをドラッグ"
Write-Host ""
Write-Host "File flow / ファイルの流れ:"
Write-Host "  Input: Voice files + Dialogue.txt → Output: Generated audio files"
Write-Host "  入力: 音声ファイル + Dialogue.txt → 出力: 生成された音声ファイル"
Write-Host ""
Write-Host "Supported formats / 対応形式: WAV, FLAC, OGG, MP3, AIFF, AU, CAF"
Write-Host "Output location / 出力先: Output フォルダ"
Write-Host ""
Write-Host "Customization / カスタマイズ:"
Write-Host "  You can edit BatchGenerate.bat to customize settings:"
Write-Host "  BatchGenerate.batを編集して設定をカスタマイズできます:"
Write-Host ""
Write-Host "  PLAY=--play --volume 0.7 --speed 1.0"
Write-Host "    Controls audio playback, volume (0.0-2.0), and speed (0.5-2.0)"
Write-Host "    音声再生、音量(0.0-2.0)、再生速度(0.5-2.0)を制御"
Write-Host "    Remove `"--play`" to disable auto-playback"
Write-Host "    `"--play`"を削除すると自動再生を無効化"
Write-Host "    Adjust `"--speed`" for faster/slower playback (1.0=normal)"
Write-Host "    `"--speed`"で再生速度を調整（1.0=通常速度）"
Write-Host ""
Write-Host "  BATCH_COUNT=1"
Write-Host "    Number of audio files to generate per text line"
Write-Host "    各テキスト行に対して生成する音声ファイル数"
Write-Host "    Increase for multiple variations of same text"
Write-Host "    同じテキストの複数バリエーション生成時に増加"
Write-Host ""
Read-Host "Press Enter to continue / Enterキーを押して続行"